### PR TITLE
Save password to .admin-password

### LINKED ISSUE #40: Automatically-generated passwords don't show up anywhere?
If you get an automatically-generated password for the admin account by leaving out the "-p" flag in "canasta create", the password that's generated doesn't seem to appear anywhere - so as far as I know it's lost forever. (If it does get stored somewhere, it would be good to know where - so that this can be noted in the documentation, and probably the CLI output as well.)

### PR DESCRIPTION
**Pull request by amalpaul54111**
Fixes #40 
Save the automatically generated password to ```.admin.password``` inside the configuration folder.

### CODE REVIEW

**Comment by yaronkoren** [comment]
This looks good! I'm looking forward to hearing what others have to say. Do you think ".admin.password" is a better name than ".admin-password"?

**Comment by amalpaul54111** [comment]
Oops!, I did misread  “.admin-password” as “.admin.password”.
".admin-password” would be better for sure.

**Review by jeffw16 — APPROVED** [review]
LGTM

**Comment by freephile** [comment]
Is this documented? Where should the feature be documented?

If you choose to have Canasta generate an admin password for you, you will find it in a file named .admin-password

**Pull request merged**
