### PR TITLE
Provide version command

### LINKED ISSUE #17: New flag: sudo canasta --version
Would `sudo canasta --version` be useful/appreciated by users?

### PR DESCRIPTION
**Pull request by hexmode**
Fixes #17

### CODE REVIEW

**Review by jeffw16 — APPROVED** [review]
LGTM

**Comment by lexsulzer** [comment]
Can this be merged?

**Comment by yaronkoren** [comment]
Sorry, has this been waiting for me the whole time to merge in? Is there any reason not to merge it in?

**Comment by jeffw16** [comment]
Let's merge it in if you don't have any objections

**Comment by yaronkoren** [comment]
Okay - I don't really understand the code (somehow Cobra is calling build.sh?), but I assume it does what it's supposed to...

**Pull request merged**
