### PR TITLE
Move CLI documentation

### PR DESCRIPTION
**Pull request by amalpaul54111**
Move CLI documentation to [Canasta Documentation](https://github.com/CanastaWiki/Canasta-Documentation)

### CODE REVIEW

**Comment by yaronkoren** [comment]
This looks fine - although the term "Command Line Interface" should appear somewhere there, I think!

**Comment by amalpaul54111** [comment]
Yeah, right. That was a mistake. Fixed it!

**Review by yaronkoren — APPROVED** [review]
Good enough!

**Comment by yaronkoren** [comment]
(This shouldn't actually be merged in until the corresponding file in Canasta-Documentation is added.)

**Pull request merged**
